# Generated by Django 6.0.3 on 2026-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=199.0, max_digits=6),
        ),
    ]
