# Generated by Django 6.0.3 on 2026-08-24 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_specialoffer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialoffer',
            name='food_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.fooditem'),
        ),
    ]
